name: ndu_dashboard_widgets
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^5.0.0
  cupertino_icons: ^0.1.3
  flutter_gauge: ^1.0.8
  charts_flutter: ^0.10.0
  flutter_flexible_toast: ^0.1.4
  flutter_webview_plugin: ^0.4.0
  web_socket_channel: ^2.1.0
  timeago: ^2.0.29
  webview_flutter: ^1.0.7
  sleek_circular_slider: ^1.2.0+web
  syncfusion_flutter_gauges: ^18.4.33
  flutter_svg: ^0.22.0
  horizontal_data_table: ^3.4.1
  synchronized: ^3.0.0
  ndu_api_client:
    path: ../ndu_api_flutter_client

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
  # To add assets to your package, add an assets section, like this:

  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
